name: CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      
      - name: install
        run: |
          python -m pip install --upgrade pip
          python -m pip install black
      - name: format code
        run: black --check upsilonconf tests
  test:
    name: test py${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ['3.6', '3.7', '3.8', '3.9']
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    steps:
      - uses: actions/checkout@v2
      
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          # python -m pip install -r requirements.txt

      - name: run tests
        run: python -m unittest discover
