name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      
      - name: install
        run: python -m pip install black

      - name: format code
        run: black --diff --check upsilonconf tests

  typecheck:
    strategy:
      matrix:
        platform: [linux, darwin, win32]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: install
        run: python -m pip install mypy types-pyyaml

      - name: check types
        run: mypy --python-version ${{ matrix.python-version }} --platform ${{ matrix.platform }} -p upsilonconf

  test:
    name: test py${{ matrix.python-version }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11']
    runs-on: ${{ format('{0}-latest', matrix.os) }}
    steps:
      - uses: actions/checkout@v2
      
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install dependencies
        run: python -m pip install -r requirements.txt

      - name: run tests
        run: python -m unittest discover
