name: CI

on:
  push:
    branches: [ main ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main ]
    paths:
      - '**.py'

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: install
        run: python -m pip install black

      - name: format code
        run: black --diff --check upsilonconf tests

  typecheck:
    name: check py${{ matrix.python-version }} types
    needs: lint
    strategy:
      matrix:
        platform: [linux, darwin, win32]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: install
        run: python -m pip install mypy types-pyyaml -r requirements.txt

      - name: check types
        run: mypy --python-version ${{ matrix.python-version }} --platform ${{ matrix.platform }} -p upsilonconf

  test:
    name: test py${{ matrix.python-version }} on ${{ matrix.os }}
    needs: typecheck
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
        exclude:
          - os: ubuntu-latest
            python-version: '3.6'
          - os: macos-latest
            python-version: '3.6'
          - os: macos-latest
            python-version: '3.7'
          - os: macos-latest
            python-version: '3.8'
          - os: macos-latest
            python-version: '3.9'
        include:
          - os: ubuntu-20.04
            python-version: '3.6'
          - os: macos-latest-large
            python-version: '3.6'
          - os: macos-latest-large
            python-version: '3.7'
          - os: macos-latest-large
            python-version: '3.8'
          - os: macos-latest-large
            python-version: '3.9'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: install dependencies
        run: python -m pip install -r requirements.txt

      - name: run tests
        run: python -m unittest discover
