name: publish-test

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: install dependencies
        run: python -m pip install build

      - name: build package
        run: python -m build

      - name: check version
        run: ls "dist/upsilonconf-${GITHUB_REF#refs/*/v}.tar.gz"

      - name: publish package test
        if: ${{ success() }}
        uses: pypa/gh-action-pypi-publish@v1.4.2
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

# TODO: once we are ready
#      - name: publish package
#        if: ${{ success() }}
#        uses: pypa/gh-action-pypi-publish@v1.4.2
#        with:
#          user: __token__
#          password: ${{ secrets.PYPI_API_TOKEN }}
