name: Sphinx build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install dependencies
        run: python -m pip install -r docs/requirements.txt

      - name: run doctests
        run: |
          cd docs
          make doctest

      - name: build HTML docs
        run: |
          cd docs
          make html

      - uses: actions/upload-artifact@v3
        with:
          name: html-docs
          path: docs/_build/html/

      - name: publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html